export const loader = {
  v: '4.8.0',
  meta: {
    g: 'LottieFiles AE 1.0.0',
    a: 'Marlon Muller',
    k: '',
    d: 'loading_cut',
    tc: '',
  },
  fr: 60,
  ip: 0,
  op: 194,
  w: 800,
  h: 800,
  nm: 'Final Comp',
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: 'RETANGLE 9',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: {
          a: 1,
          k: [
            {
              i: { x: [0.175], y: [1] },
              o: { x: [0.734], y: [0] },
              t: 46.018,
              s: [0],
            },
            { t: 106.078125, s: [180] },
          ],
          ix: 10,
        },
        p: {
          s: true,
          x: { a: 0, k: 575, ix: 3 },
          y: {
            a: 1,
            k: [
              {
                i: { x: [0.104], y: [1] },
                o: { x: [1], y: [0] },
                t: 28,
                s: [166.2],
              },
              {
                i: { x: [0.127], y: [1] },
                o: { x: [1], y: [0] },
                t: 108.08,
                s: [632.4],
              },
              { t: 191, s: [166.2] },
            ],
            ix: 4,
          },
        },
        a: { a: 0, k: [43, -3, 0], ix: 1 },
        s: { a: 0, k: [70, 70, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: { a: 0, k: [334, 334], ix: 2 },
              p: { a: 0, k: [0, 0], ix: 3 },
              r: { a: 0, k: 290, ix: 4 },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'fl',
              c: { a: 0, k: [0, 1, 1, 1], ix: 4 },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: { a: 0, k: [43, -3], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [41.722, 41.722], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 1',
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 155,
      op: 194,
      st: 28,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 2,
      ty: 4,
      nm: 'RETANGLE 8',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: {
          a: 1,
          k: [
            {
              i: { x: [0.175], y: [1] },
              o: { x: [0.734], y: [0] },
              t: 46.018,
              s: [0],
            },
            {
              i: { x: [0.557], y: [1] },
              o: { x: [1], y: [0] },
              t: 106.078,
              s: [180],
            },
            { t: 169, s: [0] },
          ],
          ix: 10,
        },
        p: {
          s: true,
          x: { a: 0, k: 575, ix: 3 },
          y: {
            a: 1,
            k: [
              {
                i: { x: [0.104], y: [1] },
                o: { x: [1], y: [0] },
                t: 28,
                s: [166.2],
              },
              {
                i: { x: [0.157], y: [1] },
                o: { x: [1], y: [0] },
                t: 108.08,
                s: [632.4],
              },
              { t: 188.16015625, s: [166.2] },
            ],
            ix: 4,
          },
        },
        a: { a: 0, k: [43, -3, 0], ix: 1 },
        s: { a: 0, k: [70, 70, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: { a: 0, k: [334, 334], ix: 2 },
              p: { a: 0, k: [0, 0], ix: 3 },
              r: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833], y: [1] },
                    o: { x: [0.167], y: [0] },
                    t: 53,
                    s: [369],
                  },
                  {
                    i: { x: [0.833], y: [1] },
                    o: { x: [0.333], y: [0] },
                    t: 81,
                    s: [1],
                  },
                  {
                    i: { x: [0.667], y: [1] },
                    o: { x: [0.333], y: [0] },
                    t: 134,
                    s: [1],
                  },
                  { t: 165, s: [369] },
                ],
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'fl',
              c: {
                a: 0,
                k: [0.30196078431372547, 0.30196078431372547, 1, 1],
                ix: 4,
              },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: { a: 0, k: [43, -3], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [41.722, 41.722], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 1',
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 72,
      op: 155,
      st: 28,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 3,
      ty: 4,
      nm: 'RETANGLE 7',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: {
          s: true,
          x: { a: 0, k: 575, ix: 3 },
          y: {
            a: 1,
            k: [
              {
                i: { x: [0.104], y: [1] },
                o: { x: [1], y: [0] },
                t: 28,
                s: [166.2],
              },
              {
                i: { x: [0.157], y: [1] },
                o: { x: [1], y: [0] },
                t: 108.08,
                s: [632.4],
              },
              { t: 188.16015625, s: [166.2] },
            ],
            ix: 4,
          },
        },
        a: { a: 0, k: [43, -3, 0], ix: 1 },
        s: { a: 0, k: [70, 70, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: { a: 0, k: [334, 334], ix: 2 },
              p: { a: 0, k: [0, 0], ix: 3 },
              r: { a: 0, k: 300, ix: 4 },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'fl',
              c: { a: 0, k: [0, 1, 1, 1], ix: 4 },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: { a: 0, k: [43, -3], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [41.722, 41.722], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 1',
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 0,
      op: 72,
      st: 28,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 4,
      ty: 4,
      nm: 'RETANGLE 6',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: {
          a: 1,
          k: [
            {
              i: { x: [0.175], y: [1] },
              o: { x: [0.734], y: [0] },
              t: 32.018,
              s: [0],
            },
            { t: 92.078125, s: [180] },
          ],
          ix: 10,
        },
        p: {
          s: true,
          x: { a: 0, k: 225, ix: 3 },
          y: {
            a: 1,
            k: [
              {
                i: { x: [0.104], y: [1] },
                o: { x: [1], y: [0] },
                t: 14,
                s: [166.2],
              },
              {
                i: { x: [0.127], y: [1] },
                o: { x: [1], y: [0] },
                t: 94.08,
                s: [632.4],
              },
              { t: 177, s: [166.2] },
            ],
            ix: 4,
          },
        },
        a: { a: 0, k: [43, -3, 0], ix: 1 },
        s: { a: 0, k: [70, 70, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: { a: 0, k: [334, 334], ix: 2 },
              p: { a: 0, k: [0, 0], ix: 3 },
              r: { a: 0, k: 290, ix: 4 },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'fl',
              c: { a: 0, k: [0, 1, 1, 1], ix: 4 },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: { a: 0, k: [43, -3], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [41.722, 41.722], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 1',
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 141,
      op: 198,
      st: 14,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 5,
      ty: 4,
      nm: 'RETANGLE 5',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: {
          a: 1,
          k: [
            {
              i: { x: [0.175], y: [1] },
              o: { x: [0.734], y: [0] },
              t: 32.018,
              s: [0],
            },
            {
              i: { x: [0.557], y: [1] },
              o: { x: [1], y: [0] },
              t: 92.078,
              s: [180],
            },
            { t: 155, s: [0] },
          ],
          ix: 10,
        },
        p: {
          s: true,
          x: { a: 0, k: 225, ix: 3 },
          y: {
            a: 1,
            k: [
              {
                i: { x: [0.104], y: [1] },
                o: { x: [1], y: [0] },
                t: 14,
                s: [166.2],
              },
              {
                i: { x: [0.157], y: [1] },
                o: { x: [1], y: [0] },
                t: 94.08,
                s: [632.4],
              },
              { t: 174.16015625, s: [166.2] },
            ],
            ix: 4,
          },
        },
        a: { a: 0, k: [43, -3, 0], ix: 1 },
        s: { a: 0, k: [70, 70, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: { a: 0, k: [334, 334], ix: 2 },
              p: { a: 0, k: [0, 0], ix: 3 },
              r: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833], y: [1] },
                    o: { x: [0.167], y: [0] },
                    t: 39,
                    s: [369],
                  },
                  {
                    i: { x: [0.833], y: [1] },
                    o: { x: [0.333], y: [0] },
                    t: 67,
                    s: [1],
                  },
                  {
                    i: { x: [0.667], y: [1] },
                    o: { x: [0.333], y: [0] },
                    t: 120,
                    s: [1],
                  },
                  { t: 151, s: [369] },
                ],
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'fl',
              c: { a: 0, k: [1, 0.9098039215686274, 0, 1], ix: 4 },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: { a: 0, k: [43, -3], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [41.722, 41.722], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 1',
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 58,
      op: 141,
      st: 14,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 6,
      ty: 4,
      nm: 'RETANGLE 4',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: {
          s: true,
          x: { a: 0, k: 225, ix: 3 },
          y: {
            a: 1,
            k: [
              {
                i: { x: [0.104], y: [1] },
                o: { x: [1], y: [0] },
                t: 14,
                s: [166.2],
              },
              {
                i: { x: [0.157], y: [1] },
                o: { x: [1], y: [0] },
                t: 94.08,
                s: [632.4],
              },
              { t: 174.16015625, s: [166.2] },
            ],
            ix: 4,
          },
        },
        a: { a: 0, k: [43, -3, 0], ix: 1 },
        s: { a: 0, k: [70, 70, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: { a: 0, k: [334, 334], ix: 2 },
              p: { a: 0, k: [0, 0], ix: 3 },
              r: { a: 0, k: 300, ix: 4 },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'fl',
              c: { a: 0, k: [0, 1, 1, 1], ix: 4 },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: { a: 0, k: [43, -3], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [41.722, 41.722], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 1',
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 0,
      op: 58,
      st: 14,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 7,
      ty: 4,
      nm: 'RETANGLE 3',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: {
          a: 1,
          k: [
            {
              i: { x: [0.175], y: [1] },
              o: { x: [0.734], y: [0] },
              t: 18.018,
              s: [0],
            },
            { t: 78.078125, s: [180] },
          ],
          ix: 10,
        },
        p: {
          s: true,
          x: { a: 0, k: 400, ix: 3 },
          y: {
            a: 1,
            k: [
              {
                i: { x: [0.104], y: [1] },
                o: { x: [1], y: [0] },
                t: 0,
                s: [166.2],
              },
              {
                i: { x: [0.127], y: [1] },
                o: { x: [1], y: [0] },
                t: 80.08,
                s: [632.4],
              },
              { t: 163, s: [166.2] },
            ],
            ix: 4,
          },
        },
        a: { a: 0, k: [43, -3, 0], ix: 1 },
        s: { a: 0, k: [70, 70, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: { a: 0, k: [334, 334], ix: 2 },
              p: { a: 0, k: [0, 0], ix: 3 },
              r: { a: 0, k: 290, ix: 4 },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'fl',
              c: { a: 0, k: [0, 1, 1, 1], ix: 4 },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: { a: 0, k: [43, -3], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [41.722, 41.722], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 1',
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 127,
      op: 197,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 8,
      ty: 4,
      nm: 'RETANGLE 2',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: {
          a: 1,
          k: [
            {
              i: { x: [0.175], y: [1] },
              o: { x: [0.734], y: [0] },
              t: 18.018,
              s: [0],
            },
            {
              i: { x: [0.557], y: [1] },
              o: { x: [1], y: [0] },
              t: 78.078,
              s: [180],
            },
            { t: 141, s: [0] },
          ],
          ix: 10,
        },
        p: {
          s: true,
          x: { a: 0, k: 400, ix: 3 },
          y: {
            a: 1,
            k: [
              {
                i: { x: [0.104], y: [1] },
                o: { x: [1], y: [0] },
                t: 0,
                s: [166.2],
              },
              {
                i: { x: [0.157], y: [1] },
                o: { x: [1], y: [0] },
                t: 80.08,
                s: [632.4],
              },
              { t: 160.16015625, s: [166.2] },
            ],
            ix: 4,
          },
        },
        a: { a: 0, k: [43, -3, 0], ix: 1 },
        s: { a: 0, k: [70, 70, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: { a: 0, k: [334, 334], ix: 2 },
              p: { a: 0, k: [0, 0], ix: 3 },
              r: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833], y: [1] },
                    o: { x: [0.167], y: [0] },
                    t: 25,
                    s: [369],
                  },
                  {
                    i: { x: [0.833], y: [1] },
                    o: { x: [0.333], y: [0] },
                    t: 53,
                    s: [1],
                  },
                  {
                    i: { x: [0.667], y: [1] },
                    o: { x: [0.333], y: [0] },
                    t: 106,
                    s: [1],
                  },
                  { t: 137, s: [369] },
                ],
                ix: 4,
              },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'fl',
              c: {
                a: 0,
                k: [
                  0.9490196078431372, 0.23921568627450981, 0.9137254901960784,
                  1,
                ],
                ix: 4,
              },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: { a: 0, k: [43, -3], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [41.722, 41.722], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 1',
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 44,
      op: 127,
      st: 0,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 9,
      ty: 4,
      nm: 'RETANGLE',
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: {
          s: true,
          x: { a: 0, k: 400, ix: 3 },
          y: {
            a: 1,
            k: [
              {
                i: { x: [0.104], y: [1] },
                o: { x: [1], y: [0] },
                t: 0,
                s: [166.2],
              },
              {
                i: { x: [0.157], y: [1] },
                o: { x: [1], y: [0] },
                t: 80.08,
                s: [632.4],
              },
              { t: 160.16015625, s: [166.2] },
            ],
            ix: 4,
          },
        },
        a: { a: 0, k: [43, -3, 0], ix: 1 },
        s: { a: 0, k: [70, 70, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: 'gr',
          it: [
            {
              ty: 'rc',
              d: 1,
              s: { a: 0, k: [334, 334], ix: 2 },
              p: { a: 0, k: [0, 0], ix: 3 },
              r: { a: 0, k: 300, ix: 4 },
              nm: 'Rectangle Path 1',
              mn: 'ADBE Vector Shape - Rect',
              hd: false,
            },
            {
              ty: 'fl',
              c: { a: 0, k: [0, 1, 1, 1], ix: 4 },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: 'Fill 1',
              mn: 'ADBE Vector Graphic - Fill',
              hd: false,
            },
            {
              ty: 'tr',
              p: { a: 0, k: [43, -3], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [41.722, 41.722], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: 'Transform',
            },
          ],
          nm: 'Rectangle 1',
          np: 2,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: 'ADBE Vector Group',
          hd: false,
        },
      ],
      ip: 0,
      op: 44,
      st: 0,
      bm: 0,
    },
  ],
  markers: [
    { tm: 44, cm: '1', dr: 0 },
    { tm: 129, cm: '2', dr: 0 },
  ],
};
