/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    colors: {
      mainBackground: '#1D1C27',
      mainBackgroundLight: '#E3EBFF',
      onPanelLight: '#E3EBFF',
      mainPanel: '#272533',
      mainPanelLight: '#F5F8FF',
      mainFontColor: '#F5F8FF',
      mainFontColorLight: '#202020',
      onPanel: '#323040',
      lighterGray: '#D8DEE6',
      lightGray: '#ACACAC',
      gray: '#7D7D7D',
      darkGray: '#525252',
      yellow: '#FFE801',
      blue: '#4D4DFE',
      pink: '#F13BE9',
      cyan: '#0CFEFF',
      purple: '#4747A5',
      darkPurple: '#37344B',
      green: '#8FCD41',
      error: '#FF756C',
      red: 'red',
      white: '#FFFFFF',
      black: '#000000',
      transparent: 'transparent',
      panelLight: 'rgba(245, 248, 255, 0.8)',
      shadowLight: 'rgba(228, 234, 248, 0.88)',
      lightBlue: '#2188FF',
    },
    fontFamily: {
      mono: ["'IBM Plex Mono'"],
      sans: ['Poppins', 'sans-serif'],
      serif: ['Poppins', 'sans-serif'],
      poppins: ['Poppins', 'sans-serif'],
      display: ['Poppins', 'sans-serif'],
      body: ['Poppins', 'sans-serif'],
    },
    extend: {
      screens: {
        xs: '360px',
      },
      fontSize: {
        xxs: ['0.625rem', { lineHeight: '0.75rem' }],
      },
      height: { 'app-tabs': '64px' },
      gridTemplateColumns: {
        'auto-1fr': 'auto 1fr',
        '1fr-auto': '1fr auto',
        '1fr-2fr': '1fr 2fr',
        '2fr-1fr': '2fr 1fr',
        '3fr-1fr': '3fr 1fr',
        '1fr-1fr': '1fr 1fr',
        '1fr-8fr': '1fr 8fr',
        '1fr-6fr-1fr': '1fr 6fr 1fr',
        'auto-1fr-auto': 'auto 1fr auto',
        'auto-auto-1fr': 'auto auto 1fr',
        '1fr-1fr-auto': '1fr 1fr auto',
        '1fr-auto-auto': '1fr auto auto',
        '2fr-1fr-auto': '2fr 1fr auto',

        '2-auto': 'repeat(2, auto)',
        '3-auto': 'repeat(3, auto)',
        '4-auto': 'repeat(4, auto)',
        'minmax-auto': 'auto minmax(0, 1fr)',
        'pipeline-skills-panel': '350px 8px 1fr',
        'docs-panel': '250px 8px 1fr 8px 350px',
        'analytics-panel': '400px 8px 1fr',
        'pipeline-panel': '450px 8px 1fr',
      },
      gridTemplateRows: {
        'auto-1fr': 'auto 1fr',
        '1fr-auto': '1fr auto',
        '1fr-9fr-1fr': '1fr 9fr 1fr',
        '1fr-1fr': '1fr 1fr',
        '1fr-2fr': '1fr 2fr',
        '2fr-1fr': '2fr 1fr',
        '1fr-8fr': '1fr 8fr',
        '1fr-6fr': '1fr 6fr',
        'auto-1fr-1fr': 'auto 1fr 1fr',
        'auto-1fr-1fr-1fr': 'auto 1fr 1fr 1fr',
        'auto-1fr-auto': 'auto 1fr auto',
        'auto-auto-1fr': 'auto auto 1fr',
        'auto-auto-auto-1fr': 'auto auto auto 1fr',
        'auto-auto-1fr-auto': 'auto auto 1fr auto',
        '1fr-1fr-auto': '1fr 1fr auto',
        '1fr-6fr-1fr': '1fr 6fr 1fr',
        '1fr-auto-auto': '1fr auto auto',
        '2-auto': 'repeat(2, auto)',
        '3-auto': 'repeat(3, auto)',
        '4-auto': 'repeat(4, auto)',
        '0.5fr-1fr': '0.5fr 1fr',
        'pipeline-input-panel': '2fr 8px 1fr',
        'pipeline-output-panel': '2fr 8px 1fr',
        'drag-3-2': '3fr 8px 2fr',
      },
    },
  },
  plugins: [],
};
